# Generated by Django 2.2.3 on 2019-07-29 23:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='published_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 7, 29, 23, 56, 43, 544392)),
        ),
    ]
