# Generated by Django 2.1.5 on 2019-08-11 03:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20190806_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='published_date',
            field=models.DateField(default=datetime.date(2019, 8, 11)),
        ),
    ]
