# Generated by Django 2.1.5 on 2019-08-11 03:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20190811_0302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 11, 3, 11, 47, 158209)),
        ),
    ]
